//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BCientificasClienteEntities : DbContext
    {
        public BCientificasClienteEntities()
            : base("name=BCientificasClienteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EasyPay> EasyPay { get; set; }
        public virtual DbSet<TarjetaCredito> TarjetaCredito { get; set; }
        public virtual DbSet<TransaccionEasyPay> TransaccionEasyPay { get; set; }
        public virtual DbSet<TransaccionTarjeta> TransaccionTarjeta { get; set; }
    
        public virtual ObjectResult<sp_Carga_EasyPay_Result> sp_Carga_EasyPay(string password, Nullable<int> easyPay_Id)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var easyPay_IdParameter = easyPay_Id.HasValue ?
                new ObjectParameter("EasyPay_Id", easyPay_Id) :
                new ObjectParameter("EasyPay_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Carga_EasyPay_Result>("sp_Carga_EasyPay", passwordParameter, easyPay_IdParameter);
        }
    
        public virtual ObjectResult<sp_Carga_TarjetaCredito_Result> sp_Carga_TarjetaCredito(string password, Nullable<int> tarjetaCredito_id)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var tarjetaCredito_idParameter = tarjetaCredito_id.HasValue ?
                new ObjectParameter("TarjetaCredito_id", tarjetaCredito_id) :
                new ObjectParameter("TarjetaCredito_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Carga_TarjetaCredito_Result>("sp_Carga_TarjetaCredito", passwordParameter, tarjetaCredito_idParameter);
        }
    
        public virtual ObjectResult<sp_Carga_TransaccionEasyPay_Result> sp_Carga_TransaccionEasyPay(string password, Nullable<int> transaccion_Id)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var transaccion_IdParameter = transaccion_Id.HasValue ?
                new ObjectParameter("Transaccion_Id", transaccion_Id) :
                new ObjectParameter("Transaccion_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Carga_TransaccionEasyPay_Result>("sp_Carga_TransaccionEasyPay", passwordParameter, transaccion_IdParameter);
        }
    
        public virtual ObjectResult<sp_Carga_TransaccionTarjeta_Result> sp_Carga_TransaccionTarjeta(string password, Nullable<int> transaccion_Id)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var transaccion_IdParameter = transaccion_Id.HasValue ?
                new ObjectParameter("Transaccion_Id", transaccion_Id) :
                new ObjectParameter("Transaccion_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Carga_TransaccionTarjeta_Result>("sp_Carga_TransaccionTarjeta", passwordParameter, transaccion_IdParameter);
        }
    
        public virtual int sp_Inserta_TransaccionEasyPay(Nullable<System.DateTime> fecha, string motivo, string resultado, Nullable<int> easyPay_Id, string password)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var motivoParameter = motivo != null ?
                new ObjectParameter("Motivo", motivo) :
                new ObjectParameter("Motivo", typeof(string));
    
            var resultadoParameter = resultado != null ?
                new ObjectParameter("Resultado", resultado) :
                new ObjectParameter("Resultado", typeof(string));
    
            var easyPay_IdParameter = easyPay_Id.HasValue ?
                new ObjectParameter("EasyPay_Id", easyPay_Id) :
                new ObjectParameter("EasyPay_Id", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_TransaccionEasyPay", fechaParameter, motivoParameter, resultadoParameter, easyPay_IdParameter, passwordParameter);
        }
    
        public virtual int sp_Inserta_TransaccionTarjeta(Nullable<System.DateTime> fecha, string motivo, string resultado, Nullable<int> tarjeta_id, string password)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var motivoParameter = motivo != null ?
                new ObjectParameter("Motivo", motivo) :
                new ObjectParameter("Motivo", typeof(string));
    
            var resultadoParameter = resultado != null ?
                new ObjectParameter("Resultado", resultado) :
                new ObjectParameter("Resultado", typeof(string));
    
            var tarjeta_idParameter = tarjeta_id.HasValue ?
                new ObjectParameter("Tarjeta_id", tarjeta_id) :
                new ObjectParameter("Tarjeta_id", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_TransaccionTarjeta", fechaParameter, motivoParameter, resultadoParameter, tarjeta_idParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_Lista_EasyPay_Result> sp_Lista_EasyPay(string password)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Lista_EasyPay_Result>("sp_Lista_EasyPay", passwordParameter);
        }
    
        public virtual ObjectResult<sp_Lista_TarjetaCredito_Result> sp_Lista_TarjetaCredito(string password)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Lista_TarjetaCredito_Result>("sp_Lista_TarjetaCredito", passwordParameter);
        }
    
        public virtual int sp_Actualiza_EasyPay(Nullable<int> easyPay_Id, string num_Cuenta, string codigo_Seguridad, string contrasena, string saldo, string password)
        {
            var easyPay_IdParameter = easyPay_Id.HasValue ?
                new ObjectParameter("EasyPay_Id", easyPay_Id) :
                new ObjectParameter("EasyPay_Id", typeof(int));
    
            var num_CuentaParameter = num_Cuenta != null ?
                new ObjectParameter("Num_Cuenta", num_Cuenta) :
                new ObjectParameter("Num_Cuenta", typeof(string));
    
            var codigo_SeguridadParameter = codigo_Seguridad != null ?
                new ObjectParameter("Codigo_Seguridad", codigo_Seguridad) :
                new ObjectParameter("Codigo_Seguridad", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            var saldoParameter = saldo != null ?
                new ObjectParameter("Saldo", saldo) :
                new ObjectParameter("Saldo", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Actualiza_EasyPay", easyPay_IdParameter, num_CuentaParameter, codigo_SeguridadParameter, contrasenaParameter, saldoParameter, passwordParameter);
        }
    
        public virtual int sp_Actualiza_TarjetaCredito(Nullable<int> tarjetaCredito_id, string numeroTarjeta, string nombreTarjeta, string mesVencimiento, string annoVencimiento, string cVV, Nullable<int> tipoTarjeta_Id, string debitoCredito, string saldo, string limite, string password)
        {
            var tarjetaCredito_idParameter = tarjetaCredito_id.HasValue ?
                new ObjectParameter("TarjetaCredito_id", tarjetaCredito_id) :
                new ObjectParameter("TarjetaCredito_id", typeof(int));
    
            var numeroTarjetaParameter = numeroTarjeta != null ?
                new ObjectParameter("NumeroTarjeta", numeroTarjeta) :
                new ObjectParameter("NumeroTarjeta", typeof(string));
    
            var nombreTarjetaParameter = nombreTarjeta != null ?
                new ObjectParameter("NombreTarjeta", nombreTarjeta) :
                new ObjectParameter("NombreTarjeta", typeof(string));
    
            var mesVencimientoParameter = mesVencimiento != null ?
                new ObjectParameter("MesVencimiento", mesVencimiento) :
                new ObjectParameter("MesVencimiento", typeof(string));
    
            var annoVencimientoParameter = annoVencimiento != null ?
                new ObjectParameter("AnnoVencimiento", annoVencimiento) :
                new ObjectParameter("AnnoVencimiento", typeof(string));
    
            var cVVParameter = cVV != null ?
                new ObjectParameter("CVV", cVV) :
                new ObjectParameter("CVV", typeof(string));
    
            var tipoTarjeta_IdParameter = tipoTarjeta_Id.HasValue ?
                new ObjectParameter("TipoTarjeta_Id", tipoTarjeta_Id) :
                new ObjectParameter("TipoTarjeta_Id", typeof(int));
    
            var debitoCreditoParameter = debitoCredito != null ?
                new ObjectParameter("DebitoCredito", debitoCredito) :
                new ObjectParameter("DebitoCredito", typeof(string));
    
            var saldoParameter = saldo != null ?
                new ObjectParameter("Saldo", saldo) :
                new ObjectParameter("Saldo", typeof(string));
    
            var limiteParameter = limite != null ?
                new ObjectParameter("Limite", limite) :
                new ObjectParameter("Limite", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Actualiza_TarjetaCredito", tarjetaCredito_idParameter, numeroTarjetaParameter, nombreTarjetaParameter, mesVencimientoParameter, annoVencimientoParameter, cVVParameter, tipoTarjeta_IdParameter, debitoCreditoParameter, saldoParameter, limiteParameter, passwordParameter);
        }
    
        public virtual int sp_Actualiza_TarjetaCredito_Saldo(Nullable<int> tarjetaCredito_id, string saldo, string password)
        {
            var tarjetaCredito_idParameter = tarjetaCredito_id.HasValue ?
                new ObjectParameter("TarjetaCredito_id", tarjetaCredito_id) :
                new ObjectParameter("TarjetaCredito_id", typeof(int));
    
            var saldoParameter = saldo != null ?
                new ObjectParameter("Saldo", saldo) :
                new ObjectParameter("Saldo", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Actualiza_TarjetaCredito_Saldo", tarjetaCredito_idParameter, saldoParameter, passwordParameter);
        }
    
        public virtual int sp_Actualiza_EasyPay_Saldo(Nullable<int> easyPay_id, string saldo, string password)
        {
            var easyPay_idParameter = easyPay_id.HasValue ?
                new ObjectParameter("EasyPay_id", easyPay_id) :
                new ObjectParameter("EasyPay_id", typeof(int));
    
            var saldoParameter = saldo != null ?
                new ObjectParameter("Saldo", saldo) :
                new ObjectParameter("Saldo", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Actualiza_EasyPay_Saldo", easyPay_idParameter, saldoParameter, passwordParameter);
        }
    }
}
