//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EasyPay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EasyPay()
        {
            this.TransaccionEasyPay = new HashSet<TransaccionEasyPay>();
        }
    
        public int EasyPay_Id { get; set; }
        public string Num_Cuenta { get; set; }
        public string Codigo_Seguridad { get; set; }
        public string Contrasena { get; set; }
        public string Saldo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransaccionEasyPay> TransaccionEasyPay { get; set; }
    }
}
