//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransaccionEasyPay
    {
        public int Transaccion_Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Motivo { get; set; }
        public string Resultado { get; set; }
        public int EasyPay_Id { get; set; }
    
        public virtual EasyPay EasyPay { get; set; }
    }
}
